Issue: 3375239 - add email scan in packages
Mellanox/libvma pull request #1074
Opened 2024-04-25 12:57 UTC by NirWolfer

Issue: [HPCINFRA-920](https://jirasw.nvidia.com/browse/HPCINFRA-920)

## Description
Add private email scan in deb/rpm packages

##### What
Make sure we dont have any private emails in rom/deb packages information or changelog

##### Why ?
RM3375239

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

2024-04-30 13:22 UTC, NirWolfer commented
bot:retest

2024-04-30 13:48 UTC, NirWolfer commented
bot:restest

2024-05-01 08:46 UTC, NirWolfer commented
bot:retest

2024-05-01 11:24 UTC, NirWolfer commented
bot:retest

2024-05-01 14:57 UTC, NirWolfer commented
bot:retest

2024-05-13 08:23 UTC, NirWolfer commented
bot:retest

2024-05-15 06:13 UTC, dpressle requested changes
missing

2024-05-15 06:13 UTC, dpressle commented on contrib/jenkins_tests/rpm.sh
> +exit $rc
Missing newline

2024-05-15 06:14 UTC, dpressle commented
please check your commits it seems like you have test commit that should be removed or squashed

2024-05-15 07:41 UTC, NirWolfer commented on contrib/jenkins_tests/rpm.sh
> +exit $rc
Newline added

2024-05-15 07:42 UTC, NirWolfer commented
Redmine test commit was squashed into the main commit

2024-05-15 09:14 UTC, dpressle approved these changes

2024-05-16 08:05 UTC, merged