[CI] issue: 4007026 Disaster recovery pipeline
Mellanox/libvma pull request #1086
Opened 2024-08-18 08:42 UTC by NirWolfer

## Description
Support for release process in DRP is required, since the envrironment is different than the prod environment there should be a new pipeline defined with said changes

##### What
Add new job template definition to release_jjb
Add new dr matrix with configuration for PDC env

##### Why ?
Issue: HPCINFRA-1889

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

2024-08-18 11:50 UTC, dpressle requested changes

2024-08-18 11:50 UTC, dpressle commented on .ci/pipeline/release_jjb.yaml
> +- job-template:
disabled: true ?

2024-08-18 11:50 UTC, dpressle commented on .ci/pipeline/release_matrix_job_dr.yaml
> +  - {file: '.ci/dockerfiles/Dockerfile.rhel8.6.release', name: 'rhel8.6', uri: '$arch/$name/release', build_args: '--no-cache', arch: 'x86_64', tag: '20240718'}
pdc harbor url ?

2024-08-18 11:50 UTC, dpressle commented on .ci/pipeline/release_jjb.yaml
> +    jjb_folder: 'libvmna'
typo libvmna

2024-08-18 12:11 UTC, NirWolfer commented on .ci/pipeline/release_jjb.yaml
> +    jjb_folder: 'libvmna'
fixed

2024-08-18 12:12 UTC, NirWolfer commented on .ci/pipeline/release_jjb.yaml
> +- job-template:
added

2024-08-18 12:13 UTC, NirWolfer commented on .ci/pipeline/release_matrix_job_dr.yaml
> +  - {file: '.ci/dockerfiles/Dockerfile.rhel8.6.release', name: 'rhel8.6', uri: '$arch/$name/release', build_args: '--no-cache', arch: 'x86_64', tag: '20240718'}
added build arg to the image

2024-08-18 12:34 UTC, dpressle submitted a review, later dismissed

2024-08-18 14:36 UTC, NirWolfer commented
bot:restest

2024-08-19 11:21 UTC, NirWolfer commented
bot:retest

2024-08-20 07:50 UTC, dpressle commented
https://nbupdc.blsm.nvidia.com/swx-media-master/job/libvma/job/LibVMA-release-dr/3/

2024-08-20 07:53 UTC, NirWolfer commented
bot:lin:retest

2024-08-20 07:54 UTC, NirWolfer commented
bot:retest

2024-08-20 09:03 UTC, NirWolfer commented
bot:retest

2024-08-20 11:20 UTC, NirWolfer commented
bot:retest

2024-08-20 13:16 UTC, NirWolfer commented
bot:retest

2024-08-21 08:35 UTC, NirWolfer commented
bot:retest

2024-08-22 06:08 UTC, dpressle commented
bot:retest

2024-08-22 06:17 UTC, dpressle commented
bot:retest

2024-08-22 14:17 UTC, NirWolfer commented
bot:retest

2024-08-27 08:55 UTC, dpressle commented
bot:rm:retest

2024-08-27 08:58 UTC, dpressle approved these changes

2024-08-27 10:10 UTC, merged